DROP TABLE KEY_VAL_MAIN CASCADE CONSTRAINTS;
DROP TABLE KEY_VAL_CHILD CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_KEY_VAL_MAIN;

DROP TABLE CHUNK_MAIN CASCADE CONSTRAINTS;
DROP TABLE CHUNK_CHILD CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CHUNK_MAIN;

