DROP TABLE KEY_VAL_MAIN CASCADE CONSTRAINTS;
DROP TABLE KEY_VAL_CHILD CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_KEY_VAL_MAIN;

DROP TABLE MAIN_CHUNK CASCADE CONSTRAINTS;
DROP TABLE CHILD_CHUNK CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MAIN_CHUNK;

