CREATE TABLE MAIN_CHUNK (
  ID             NUMBER(18) PRIMARY KEY,
  EDIT_DATE      TIMESTAMP(3)        NOT NULL,
  AS_NAME        VARCHAR2(4000 CHAR) NOT NULL,
  OPERATION_TYPE VARCHAR2(4000 CHAR) NOT NULL,
  OPERATION_ID   NUMBER(18)          NOT NULL
);

CREATE SEQUENCE SEQ_MAIN_CHUNK CACHE 100;

CREATE TABLE CHILD_CHUNK (
  MAIN_ID    NUMBER(18)          NOT NULL,
  CHUNK_NUM  NUMBER(18)          NOT NULL,
  CHUNK_DATA VARCHAR2(4000 CHAR) NOT NULL,

  CONSTRAINT FK_CHILD_CHUNK_MAIN
  FOREIGN KEY (MAIN_ID)
  REFERENCES MAIN_CHUNK (ID)
);

CREATE INDEX IDX_CC_MAIN_ID
  ON CHILD_CHUNK (MAIN_ID);

