DROP TABLE MAIN_KEY_VAL CASCADE CONSTRAINTS;
DROP TABLE CHILD_KEY_VAL CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MAIN_KEY_VAL;

DROP TABLE MAIN_CHUNK CASCADE CONSTRAINTS;
DROP TABLE CHILD_CHUNK CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MAIN_CHUNK;

